hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "4869441dabda853f7f71848c5f369a3fb90aaf5b53e5db6f70e4a09b26745dd0"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "ed79add649e0eeb5813ad948884292a353219faa5e84b927d8e4d1c22aac0ed6"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "1c640d8a9d60f3d0799e4f841c30845651406acb24f4519e79d6391e42ed320a"

[[files]]
file = "config/yosbr/config/headpats.json"
hash = "377cf0a4c8f384ee6d5fa593ab0c52e7a4ef30baf5c0f770d9b630869d38b6b9"

[[files]]
file = "config/yosbr/config/transmog.json"
hash = "32dc3ac1fa365cdb995745924a850b8f36c11621e092d305ded2cb780dad7f0f"

[[files]]
file = "config/yosbr/options.txt"
hash = "94b2f1aa6e36b9c168a29f02469fe485f1e1100d44df242b45c79b7416d9dc5b"

[[files]]
file = "icon.png"
hash = "d64a93e6bf913b68b4caef88cf5590b540899d23399b52a32179942aa6a0126a"

[[files]]
file = "mods/accessories.pw.toml"
hash = "97befad2275e44c557794fbd321b154510279ce7906426607288062e096df86d"
metafile = true

[[files]]
file = "mods/blahaj-of-undying.pw.toml"
hash = "7d7d8786ecd70b09670f838a0318cdbe6139e48aa757f53064004a62d49909c7"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "e5196147e561521c5a3ebaea601191e442d252cc8f0a7be8ba8db136f93c44fe"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/coleus.pw.toml"
hash = "5fae348e5da1df479923a01b64dd5e2514fcc772c91a49b996cde262fe07819a"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "eecdc8127f69c74ff55fd183d1f1d7d5ef3e714d73845a239fe9e086147a67b1"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "8b0b277d0995973ec6110af87f836f02699365bd072e52a4543ca56aa317fb6d"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "76ab02862f59837b93cbfacfdfb722dfaf3fe5198db43ee884f61ad738a3f589"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "60e6720aafdfa3304b086f7465917179485a3b2463230505728bd24d54113de3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "4ed0328f3789ce169f8a338f2889f47ebb3b2de44dc9a3fe5934ddf2f4141179"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "a1f1206514a1311c556b5e5542dac4acc1d239c9dc6120efe7b7495245376cfb"
metafile = true

[[files]]
file = "mods/headpat.pw.toml"
hash = "476cee1d0c5080061c4cc609f692028b118f7084e22dfed8b8f709550465cffc"
metafile = true

[[files]]
file = "mods/illusionist.pw.toml"
hash = "1f8cd3cbc0c837c957dd24bcab07888593cea0bc5d12ad65d7991a0d1e6e7b8d"
metafile = true

[[files]]
file = "mods/lavender.pw.toml"
hash = "7dc27df21d8bd6b4e5387592063817c7de24a7e3ce8c90bb6bf3a9e22199d5e5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/moderate-loading-screen.pw.toml"
hash = "db37c68027116ff4236579cc8777c505d62edaa6d65cba2bbcd6d9684f434d43"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "5d25233fba3660f080fdf112e1599ce4365183930b2385dfd9591d32ed0be29a"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "110132a70b524eaadb750bc110c9344d84432da97a5434ae185e815d778d21f0"
metafile = true

[[files]]
file = "mods/partytrick.pw.toml"
hash = "f4c70c6c9105435e6100b6c1844b382a1a5003f3284821cb98c17569844b8654"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "8302da862578554b012b2cfe58a3c1e75b514d09f94d842e7303be41a2157aeb"
metafile = true

[[files]]
file = "mods/shuttfup.pw.toml"
hash = "e4891e76bc72c6b2cc0443679b7412506e32bddcb0648539cc7781d3bfb045c7"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1af09f16a643df0f61f2c799e981aa0b8c109999f0784584a6eff9a81f1c00c1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/transmog.pw.toml"
hash = "8b08d401ea44b5d0a5c537afca6a87e280b0438c394ce978b6049a1f6d66eaa4"
metafile = true

[[files]]
file = "mods/trickster-math-tricks.pw.toml"
hash = "3b787f6e9ab500cc6037b3dfeeb9830d765c3d976e9cb37b02c0c75ae899f08c"
metafile = true

[[files]]
file = "mods/trickster.pw.toml"
hash = "db0306af280a7691f4127f8fe853d7924c7a741fcd31e878c3e61f28d0f585f2"
metafile = true

[[files]]
file = "mods/xanders-sodium-options.pw.toml"
hash = "37b68508d279d982bd0c0b970f8e331acf006edcaab653ef5869b702c21b73b1"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true
