name = "A Trickster Modpack"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b579a35c754a43736df8d72cfeb36ad6e0d922b420781278ca31f7f7ce2edd3b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
