name = "A Trickster Modpack"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa8bae3dc208883b223289439cc87c52ece1aa28df16ff4f190bc035a4d0cf04"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
